/**
 * @doc color set 颜色集合
 * @author Heanes",
 * @time 2017-05-27 16:59:48 周六
 */
var colorNameSet = {
    aliceBlue:            "#f0f8ff",
    antiqueWhite:         "#faebd7",
    aqua:                 "#00ffff",
    aquaMarine:           "#7fffd4",
    azure:                "#f0ffff",
    beige:                "#f5f5dc",
    bisque:               "#ffe4c4",
    black:                "#000000",
    blanchedAlmond:       "#ffebcd",
    blue:                 "#0000ff",
    blueViolet:           "#8a2be2",
    brown:                "#a52a2a",
    burlyWood:            "#deb887",
    cadetBlue:            "#5f9ea0",
    chartreuse:           "#7fff00",
    chocolate:            "#d2691e",
    coral:                "#ff7f50",
    cornflowerBlue:       "#6495ed",
    cornsilk:             "#fff8dc",
    crimson:              "#dc143c",
    cyan:                 "#00ffff",
    darkBlue:             "#00008b",
    darkCyan:             "#008b8b",
    darkGoldenRod:        "#b8860b",
    darkGray:             "#a9a9a9",
    darkGreen:            "#006400",
    darkGrey:             "#a9a9a9",
    darkKhaki:            "#bdb76b",
    darkMagenta:          "#8b008b",
    darkOliveGreen:       "#556b2f",
    darkOrange:           "#ff8c00",
    darkOrchid:           "#9932cc",
    darkRed:              "#8b0000",
    darkSalmon:           "#e9967a",
    darkSeaGreen:         "#8fbc8f",
    darkSlateBlue:        "#483d8b",
    darkSlateGray:        "#2f4f4f",
    darkSlateGrey:        "#2f4f4f",
    darkTurquoise:        "#00ced1",
    darkViolet:           "#9400d3",
    deepPink:             "#ff1493",
    deepSkyBlue:          "#00bfff",
    dimGray:              "#696969",
    dimGrey:              "#696969",
    dodgerBlue:           "#1e90ff",
    fireBrick:            "#b22222",
    floralWhite:          "#fffaf0",
    forestGreen:          "#228b22",
    fuchsia:              "#ff00ff",
    gainsboro:            "#dcdcdc",
    ghostWhite:           "#f8f8ff",
    gold:                 "#ffd700",
    goldenRod:            "#daa520",
    gray:                 "#808080",
    green:                "#008000",
    greenYellow:          "#adff2f",
    grey:                 "#808080",
    honeyDew:             "#f0fff0",
    hotPink:              "#ff69b4",
    indianRed:            "#cd5c5c",
    indigo:               "#4b0082",
    ivory:                "#fffff0",
    khaki:                "#f0e68c",
    lavender:             "#e6e6fa",
    lavenderBlush:        "#fff0f5",
    lawnGreen:            "#7cfc00",
    lemonChiffon:         "#fffacd",
    lightBlue:            "#add8e6",
    lightCoral:           "#f08080",
    lightCyan:            "#e0ffff",
    lightGoldenRodYellow: "#fafad2",
    lightGray:            "#d3d3d3",
    lightGreen:           "#90ee90",
    lightGrey:            "#d3d3d3",
    lightPink:            "#ffb6c1",
    lightSalmon:          "#ffa07a",
    lightSeaGreen:        "#20b2aa",
    lightSkyBlue:         "#87cefa",
    lightSlateGray:       "#778899",
    lightSlateGrey:       "#778899",
    lightSteelBlue:       "#b0c4de",
    lightYellow:          "#ffffe0",
    lime:                 "#00ff00",
    limeGreen:            "#32cd32",
    linen:                "#faf0e6",
    magenta:              "#ff00ff",
    maroon:               "#800000",
    mediumAquaMarine:     "#66cdaa",
    mediumBlue:           "#0000cd",
    mediumOrchid:         "#ba55d3",
    mediumPurple:         "#9370db",
    mediumSeaGreen:       "#3cb371",
    mediumSlateBlue:      "#7b68ee",
    mediumSpringGreen:    "#00fa9a",
    mediumTurquoise:      "#48d1cc",
    mediumVioletRed:      "#c71585",
    midnightBlue:         "#191970",
    mintCream:            "#f5fffa",
    mistyRose:            "#ffe4e1",
    moccasin:             "#ffe4b5",
    navajoWhite:          "#ffdead",
    navy:                 "#000080",
    oldlace:              "#fdf5e6",
    olive:                "#808000",
    oliveDrab:            "#6b8e23",
    orange:               "#ffa500",
    orangeRed:            "#ff4500",
    orchid:               "#da70d6",
    paleGoldenRod:        "#eee8aa",
    paleGreen:            "#98fb98",
    paleTurquoise:        "#afeeee",
    paleVioletRed:        "#db7093",
    papayaWhip:           "#ffefd5",
    peachPuff:            "#ffdab9",
    peru:                 "#cd853f",
    pink:                 "#ffc0cb",
    plum:                 "#dda0dd",
    powderBlue:           "#b0e0e6",
    purple:               "#800080",
    red:                  "#ff0000",
    rosyBrown:            "#bc8f8f",
    royalBlue:            "#4169e1",
    saddleBrown:          "#8b4513",
    salmon:               "#fa8072",
    sandyBrown:           "#f4a460",
    seaGreen:             "#2e8b57",
    seaShell:             "#fff5ee",
    sienna:               "#a0522d",
    silver:               "#c0c0c0",
    skyBlue:              "#87ceeb",
    slateBlue:            "#6a5acd",
    slateGray:            "#708090",
    slateGrey:            "#708090",
    snow:                 "#fffafa",
    springGreen:          "#00ff7f",
    steelBlue:            "#4682b4",
    tan:                  "#d2b48c",
    teal:                 "#008080",
    thistle:              "#d8bfd8",
    tomato:               "#ff6347",
    turquoise:            "#40e0d0",
    violet:               "#ee82ee",
    wheat:                "#f5deb3",
    white:                "#ffffff",
    whiteSmoke:           "#f5f5f5",
    yellow:               "#ffff00",
    yellowGreen:          "#9acd32",
};

var colorNameSetOrderByValue = {
    white:"#ffffff",
    ivory:"#fffff0",
    lightYellow:"#ffffe0",
    yellow:"#ffff00",
    snow:"#fffafa",
    floralWhite:"#fffaf0",
    lemonChiffon:"#fffacd",
    cornsilk:"#fff8dc",
    seaShell:"#fff5ee",
    lavenderBlush:"#fff0f5",
    papayaWhip:"#ffefd5",
    blanchedAlmond:"#ffebcd",
    mistyRose:"#ffe4e1",
    bisque:"#ffe4c4",
    moccasin:"#ffe4b5",
    navajoWhite:"#ffdead",
    peachPuff:"#ffdab9",
    gold:"#ffd700",
    pink:"#ffc0cb",
    lightPink:"#ffb6c1",
    orange:"#ffa500",
    lightSalmon:"#ffa07a",
    darkOrange:"#ff8c00",
    coral:"#ff7f50",
    hotPink:"#ff69b4",
    tomato:"#ff6347",
    orangeRed:"#ff4500",
    deepPink:"#ff1493",
    fuchsia:"#ff00ff",
    magenta:"#ff00ff",
    red:"#ff0000",
    oldlace:"#fdf5e6",
    lightGoldenRodYellow:"#fafad2",
    linen:"#faf0e6",
    antiqueWhite:"#faebd7",
    salmon:"#fa8072",
    ghostWhite:"#f8f8ff",
    mintCream:"#f5fffa",
    whiteSmoke:"#f5f5f5",
    beige:"#f5f5dc",
    wheat:"#f5deb3",
    sandyBrown:"#f4a460",
    azure:"#f0ffff",
    honeyDew:"#f0fff0",
    aliceBlue:"#f0f8ff",
    khaki:"#f0e68c",
    lightCoral:"#f08080",
    paleGoldenRod:"#eee8aa",
    violet:"#ee82ee",
    darkSalmon:"#e9967a",
    lavender:"#e6e6fa",
    lightCyan:"#e0ffff",
    burlyWood:"#deb887",
    plum:"#dda0dd",
    gainsboro:"#dcdcdc",
    crimson:"#dc143c",
    paleVioletRed:"#db7093",
    goldenRod:"#daa520",
    orchid:"#da70d6",
    thistle:"#d8bfd8",
    lightGray:"#d3d3d3",
    lightGrey:"#d3d3d3",
    tan:"#d2b48c",
    chocolate:"#d2691e",
    peru:"#cd853f",
    indianRed:"#cd5c5c",
    mediumVioletRed:"#c71585",
    silver:"#c0c0c0",
    darkKhaki:"#bdb76b",
    rosyBrown:"#bc8f8f",
    mediumOrchid:"#ba55d3",
    darkGoldenRod:"#b8860b",
    fireBrick:"#b22222",
    powderBlue:"#b0e0e6",
    lightSteelBlue:"#b0c4de",
    paleTurquoise:"#afeeee",
    greenYellow:"#adff2f",
    lightBlue:"#add8e6",
    darkGray:"#a9a9a9",
    darkGrey:"#a9a9a9",
    brown:"#a52a2a",
    sienna:"#a0522d",
    yellowGreen:"#9acd32",
    darkOrchid:"#9932cc",
    paleGreen:"#98fb98",
    darkViolet:"#9400d3",
    mediumPurple:"#9370db",
    lightGreen:"#90ee90",
    darkSeaGreen:"#8fbc8f",
    saddleBrown:"#8b4513",
    darkMagenta:"#8b008b",
    darkRed:"#8b0000",
    blueViolet:"#8a2be2",
    lightSkyBlue:"#87cefa",
    skyBlue:"#87ceeb",
    gray:"#808080",
    grey:"#808080",
    olive:"#808000",
    purple:"#800080",
    maroon:"#800000",
    aquamarine:"#7fffd4",
    chartreuse:"#7fff00",
    lawnGreen:"#7cfc00",
    mediumSlateBlue:"#7b68ee",
    lightSlateGray:"#778899",
    lightSlateGrey:"#778899",
    slateGray:"#708090",
    slateGrey:"#708090",
    oliveDrab:"#6b8e23",
    slateBlue:"#6a5acd",
    dimGray:"#696969",
    dimGrey:"#696969",
    mediumAquaMarine:"#66cdaa",
    cornflowerBlue:"#6495ed",
    cadetBlue:"#5f9ea0",
    darkOliveGreen:"#556b2f",
    indigo:"#4b0082",
    mediumTurquoise:"#48d1cc",
    darkSlateBlue:"#483d8b",
    steelBlue:"#4682b4",
    royalBlue:"#4169e1",
    turquoise:"#40e0d0",
    mediumSeaGreen:"#3cb371",
    limeGreen:"#32cd32",
    darkSlateGray:"#2f4f4f",
    darkSlateGrey:"#2f4f4f",
    seaGreen:"#2e8b57",
    forestGreen:"#228b22",
    lightSeaGreen:"#20b2aa",
    dodgerBlue:"#1e90ff",
    midnightBlue:"#191970",
    aqua:"#00ffff",
    cyan:"#00ffff",
    springGreen:"#00ff7f",
    lime:"#00ff00",
    mediumSpringGreen:"#00fa9a",
    darkTurquoise:"#00ced1",
    deepSkyBlue:"#00bfff",
    darkCyan:"#008b8b",
    teal:"#008080",
    green:"#008000",
    darkGreen:"#006400",
    blue:"#0000ff",
    mediumBlue:"#0000cd",
    darkBlue:"#00008b",
    navy:"#000080",
    black:"#000000"
};

function generateColorStyle(colorMap, classNamePrefix, styleAttribute) {
    var str = '';
    $.each(colorMap, function (key, item) {
        str += '\n' + classNamePrefix + '.' + key + '{\n' + styleAttribute + ':' + item +';\n}\n';
        //str += '<div class="color-name-set-show-block ' + key + '">' + key + '</div>';
    });
    return str;
}
//var style = '<pre>' + generateColorStyle(colorNameSet, '.color-name-set-show-block', 'background-color') + '</pre>';
var style = '<pre>' + generateColorStyle(colorNameSetOrderByValue, '', 'background-color') + '</pre>';
$('body').append(style);