/* Automatically generated by './build/bin/build-entry.js' */

import Row from './components/row/index.js';
import Col from './components/col/index.js';
import ButtonGroup from './components/button-group/index.js';
import Button from './components/button/index.js';
import Icon from './components/icon/index.js';
import Scrollbar from './components/scrollbar/index.js';
import Input from './components/input/index.js';
import Select from './components/select/index.js';
import Option from './components/option/index.js';
import Table from './components/table/index.js';
import Pagination from './components/pagination/index.js';
import Navigation from './components/navigation/index.js';
import Tabs from './components/tabs/index.js';
import Alert from './components/alert/index.js';
import Message from './components/message/index.js';
import Notification from './components/notification/index.js';

const components = [
  Row,
  Col,
  ButtonGroup,
  Button,
  Icon,
  Scrollbar,
  Input,
  Select,
  Option,
  Table,
  Pagination,
  Navigation,
  Tabs,
  Alert,
  Message,
  Notification
];

const install = function(Vue, opts = {}) {
  components.forEach(component => {
    Vue.component(component.name, component);
  });
  Vue.prototype.$message = Message;
  Vue.prototype.$alert = Alert;
  Vue.prototype.$tip = Alert;
};

if (typeof window !== 'undefined' && window.Vue) {
  install(window.Vue);
}

export default {
  version: '1.0.0',
  install,
  Row,
  Col,
  ButtonGroup,
  Button,
  Icon,
  Scrollbar,
  Input,
  Select,
  Option,
  Table,
  Pagination,
  Navigation,
  Tabs,
  Alert,
  Message,
  Notification
}
